# tasks file
---
- name: configure | stat directories
  stat:
    path: "{{ item }}/"
  register: _stat_directories
  with_items:
    - "{{ twisted_connect_proxy_log_file | dirname }}"
  tags:
    - twisted-connect-proxy-configure-directories
    - twisted-connect-proxy-configure-directories-stat

- name: configure | create directories
  file:
    path: "{{ item.item }}"
    state: directory
    owner: "{{ twisted_connect_proxy_user }}"
    group: "{{ twisted_connect_proxy_group }}"
    mode: 0755
  with_items: "{{ _stat_directories.results }}"
  when: item.stat is defined and not item.stat.exists
  tags:
    - twisted-connect-proxy-configure-directories
    - twisted-connect-proxy-configure-directories-create

- name: configure | update configuration file(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: "{{ twisted_connect_proxy_etc_default_file.lstrip('/') }}.j2"
      dest: "{{ twisted_connect_proxy_etc_default_file }}"
  notify: restart twisted-connect-proxy
  tags:
    - twisted-connect-proxy-configure-configuration
