# tasks file for twisted-connect-proxy
---
- name: install | dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ twisted_connect_proxy_dependencies }}"
  tags:
    - twisted-connect-proxy-install-dependencies

- name: install | create (download) directory
  file:
    path: "{{ twisted_connect_proxy_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - twisted-connect-proxy-install-download
    - twisted-connect-proxy-install-download-directory

- name: install | download
  get_url:
    url: "https://raw.githubusercontent.com/fmoo/twisted-connect-proxy/{{ twisted_connect_proxy_version }}/server.py"
    dest: "{{ twisted_connect_proxy_downloads_path }}/server.py"
    owner: root
    group: root
    mode: 0755
    force: true
  notify: restart twisted-connect-proxy
  tags:
    - twisted-connect-proxy-install-download
    - twisted-connect-proxy-install-download-get

- name: install | install
  file:
    src: "{{ twisted_connect_proxy_downloads_path }}/server.py"
    dest: "{{ twisted_connect_proxy_install_prefix }}/twisted-connect-proxy"
    state: link
    force: true
  tags:
    - twisted-connect-proxy-install-install
    - twisted-connect-proxy-install-install-symlink
