# tasks file
---
- name: facts | set
  ansible.builtin.set_fact:
    is_docker_guest: "{{ ansible_virtualization_role | default('host') == 'guest' and ansible_virtualization_type | default('none') == 'docker' }}"
  tags:
    - configuration
    - twisted-connect
    - twisted-connect-facts

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - twisted-connect-proxy
    - twisted-connect-proxy-install

- name: user
  ansible.builtin.import_tasks: user.yml
  tags:
    - configuration
    - twisted-connect-proxy
    - twisted-connect-proxy-user

- name: configure
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configuration
    - twisted-connect
    - twisted-connect-configure

- name: docker guest
  when: is_docker_guest
  tags:
    - configuration
    - twisted-connect
    - twisted-connect-service
    - twisted-connect-service-initd
  block:
    - name: service initd
      ansible.builtin.import_tasks: service-initd.yml

- name: not docker guest
  when: not is_docker_guest
  tags:
    - configuration
    - twisted-connect
    - twisted-connect-service
  block:
    - name: service upstart
      ansible.builtin.import_tasks: service-upstart.yml
      when: ansible_service_mgr != 'systemd'
      tags:
        - twisted-connect-service-upstart

    - name: service systemd
      ansible.builtin.import_tasks: service-systemd.yml
      when: ansible_service_mgr == 'systemd'
      tags:
        - twisted-connect-service-systemd

- name: start and enable service
  ansible.builtin.service:
    name: twisted-connect-proxy
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - twisted-connect-proxy
    - twisted-connect-proxy-start-enable-service
