# tasks file
---
- name: facts | set
  set_fact:
    is_docker_guest: "{{ ansible_virtualization_role | default('host') == 'guest' and ansible_virtualization_type | default('none') == 'docker' }}"
  tags:
    - configuration
    - twisted-connect
    - twisted-connect-facts

- include: install.yml
  tags:
    - configuration
    - twisted-connect-proxy
    - twisted-connect-proxy-install

- include: user.yml
  tags:
    - configuration
    - twisted-connect-proxy
    - twisted-connect-proxy-user

- include: configure.yml
  tags:
    - configuration
    - twisted-connect
    - twisted-connect-configure

- block:
    - include: service-initd.yml
  when: is_docker_guest
  tags:
    - configuration
    - twisted-connect
    - twisted-connect-service
    - twisted-connect-service-initd

- block:
    - include: service-upstart.yml
      when: ansible_service_mgr != 'systemd'
      tags:
        - twisted-connect-service-upstart

    - include: service-systemd.yml
      when: ansible_service_mgr == 'systemd'
      tags:
        - twisted-connect-service-systemd
  when: not is_docker_guest
  tags:
    - configuration
    - twisted-connect
    - twisted-connect-service

- name: start and enable service
  service:
    name: twisted-connect-proxy
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - twisted-connect-proxy
    - twisted-connect-proxy-start-enable-service
