# tasks file for twisted-connect-proxy
---
- name: service | upstart | update script
  template:
    src: "{{ twisted_connect_proxy_etc_init_file.lstrip('/') }}.j2"
    dest: "{{ twisted_connect_proxy_etc_init_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart twisted-connect-proxy
  tags:
    - twisted-connect-proxy-service-upstart-update
