# tasks file for twisted-connect-proxy
---
- name: service | systemd | update script
  template:
    src: templates/lib/systemd/system/twisted-connect-proxy.j2
    dest: /lib/systemd/system/twisted-connect-proxy.service
    owner: root
    group: root
    mode: 0644
  register: _update_systemd_script
  notify: restart twisted-connect-proxy
  tags:
    - twisted-connect-proxy-service-systemd-update

- name: service | systemd | reload
  command: systemctl daemon-reload
  when: _update_systemd_script | changed
  tags:
    - twisted-connect-proxy-service-systemd-reload
