# tasks file for twisted-connect-proxy
---
- name: service | upstart | update script
  template:
    src: etc/init/twisted-connect-proxy.conf.j2
    dest: /etc/init/twisted-connect-proxy.conf
    owner: root
    group: root
    mode: 0644
  notify: restart twisted-connect-proxy
  tags:
    - twisted-connect-proxy-service-upstart-update
