# tasks file for twisted-connect-proxy
---
- name: service | systemd | update script
  template:
    src: "{{ twisted_connect_proxy_etc_systemd_file.lstrip('/') }}.j2"
    dest: "{{ twisted_connect_proxy_etc_systemd_file }}"
    owner: root
    group: root
    mode: 0644
  register: _update_systemd_script
  notify: restart twisted-connect-proxy
  tags:
    - twisted-connect-proxy-service-systemd-update

- name: service | systemd | reload
  systemd:
    daemon_reload: true
  when: _update_systemd_script is changed
  tags:
    - twisted-connect-proxy-service-systemd-reload
