# tasks file for twisted-connect-proxy
---
- name: add group
  group:
    name: "{{ item }}"
  with_flattened:
    - "{{ twisted_connect_proxy_group }}"
    - "{{ twisted_connect_proxy_groups }}"
  tags:
    - twisted-connect-proxy-user-add
    - twisted-connect-proxy-user-add-group

- name: add user
  user:
    name: "{{ twisted_connect_proxy_user }}"
    group: "{{ twisted_connect_proxy_group }}"
    groups: "{{ twisted_connect_proxy_groups | join(',') }}"
    home: /nonexistent
    shell: /usr/sbin/nologin
  tags:
    - twisted-connect-proxy-user-add
    - twisted-connect-proxy-user-add-user
