# tasks file
---
- name: user | add group
  ansible.builtin.group:
    name: "{{ item }}"
    system: true
  with_items: "{{ [twisted_connect_proxy_group] + twisted_connect_proxy_groups }}"
  tags:
    - twisted-connect-proxy-user-add
    - twisted-connect-proxy-user-add-group

- name: user | add user
  ansible.builtin.user:
    name: "{{ twisted_connect_proxy_user }}"
    system: true
    group: "{{ twisted_connect_proxy_group }}"
    groups: "{{ twisted_connect_proxy_groups | join(',') }}"
    home: /nonexistent
    shell: /usr/sbin/nologin
  tags:
    - twisted-connect-proxy-user-add
    - twisted-connect-proxy-user-add-user
