# handlers file
---
- name: restart twisted-connect-proxy
  ansible.builtin.service:
    name: twisted-connect-proxy
    state: restarted
  when: service_default_state | default('started') == 'started'
