# handlers file for twisted-connect-proxy
---
- name: restart twisted-connect-proxy
  service:
    name: twisted-connect-proxy
    state: restarted
  when: service_default_state | default('started') == 'started'
